services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./uploads:/app/uploads
      - ./models:/models
      - kuzu_data:/data/kuzu
      - huggingface_cache:/root/.cache/huggingface
      - torch_cache:/root/.cache/torch


volumes:
  kuzu_data:
    driver: local
  huggingface_cache:  # Add this volume
    driver: local
  torch_cache:  # Add this volume
    driver: local