version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./uploads:/app/uploads
    environment:
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
    depends_on:
      - falkordb

  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379"
    volumes:
      - falkordb_data:/data
    command: ["redis-server", "--loadmodule", "/usr/lib/redis/modules/falkordb.so"]

volumes:
  falkordb_data:
