services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./uploads:/app/uploads
      - ./models:/models
      - kuzu_data:/data/kuzu

volumes:
  kuzu_data:
    driver: local