services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./uploads:/app/uploads
    environment:
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379
    depends_on:
      - falkordb

  falkordb:
    image: falkordb/falkordb:v4.8.5-arm64v8
    ports:
      - "6379:6379"
    volumes:
      - falkordb_data:/data

volumes:
  falkordb_data:
